<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2005 sp2 U (http://www.altova.com) by  () -->
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:y="http://JSTV/PublicService/AuthentificationService/" xmlns:ns="http://JSTV/MediaEntityDefinition/" xmlns:ns1="http://JSTV/PaySystem/Parameter" targetNamespace="http://JSTV/PublicService/AuthentificationService/">
	<types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:PSP="http://JSTV/PaySystem/Parameter" targetNamespace="empty" elementFormDefault="qualified">
			<xsd:import namespace="http://JSTV/PaySystem/Parameter" schemaLocation="..\计费系统\PayServiceParameter.xsd"/>
		</xsd:schema>
	</types>
	<message name="ReceiveSynUserRequestMessage">
		<part name="ReceiveSynUserRequest" element="ns1:SynUserRequest"/>
	</message>
	<message name="ReceiveSynUserResponseMessage">
		<part name="ReceiveSynUserResponse" element="ns1:SynUserResponse"/>
	</message>
	<portType name="ReceiveSynUserPortType">
		<operation name="synUser">
			<input message="y:ReceiveSynUserRequestMessage"/>
			<output message="y:ReceiveSynUserResponseMessage"/>
		</operation>
	</portType>
	<binding name="ReceiveSynUserBinding" type="y:ReceiveSynUserPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="synUser">
			<soap:operation/>
			<input>
				<soap:body use="literal"/>
			</input>
			<output>
				<soap:body use="literal"/>
			</output>
		</operation>
	</binding>
	<service name="AuthentificationService">
		<port name="AuthentificationPort" binding="y:ReceiveSynUserBinding">
			<soap:address location="No Target Adress"/>
		</port>
	</service>
</definitions>
