<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2005 sp2 U (http://www.altova.com) by any (Ru-Board) -->
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:y="http://JSTV/PublicService/ExportAllowService/" xmlns:ns="http://JSTV/MediaEntityDefinition/" xmlns:ns1="http://JSTV/PublicService/Parameter/" xmlns:ns2="http://JSTV/PaySystem/Parameter" targetNamespace="http://JSTV/PublicService/ExportAllowService/">
	<types>
		<xs:schema xmlns:tns="http://JSTV/PublicService/Parameter/">
			<xs:import namespace="http://JSTV/PublicService/Parameter/" schemaLocation="PublicServiceParameter.xsd"/>
		</xs:schema>
	</types>
	<message name="ExportAllowRequestMessage">
		<part name="ExportAllowRequest" element="ns1:ExportAllowRequest"/>
	</message>
	<portType name="ExportAllowPortType">
		<operation name="preCheck">
			<input message="y:ExportAllowRequestMessage"/>
		</operation>
	</portType>
	<binding name="ExportAllowBinding" type="y:ExportAllowPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="preCheck">
			<input>
				<soap:body use="literal"/>
			</input>
		</operation>
	</binding>
	<service name="ExportAllowService">
		<port name="ExportAllowPort" binding="y:ExportAllowBinding">
			<soap:address location="No Target Adress"/>
		</port>
	</service>
</definitions>
