<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2005 sp2 U (http://www.altova.com) by  () -->
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:y="http://JSTV/PublicService/ExportAllowAsynCallbackService/" xmlns:ns="http://JSTV/MediaEntityDefinition/" xmlns:ns1="http://JSTV/PaySystem/Parameter" xmlns:ns2="http://JSTV/PublicService/Parameter/" targetNamespace="http://JSTV/PublicService/ExportAllowAsynCallbackService/">
	<types>
		<xs:schema xmlns:tns="http://JSTV/PublicService/Parameter/">
			<xs:import namespace="http://JSTV/PublicService/Parameter/" schemaLocation="PublicServiceParameter.xsd"/>
		</xs:schema>
	</types>
	<message name="ExportAllowCallbackInputMessage">
		<part name="ExportAllowCallbackInput" element="ns2:ExportAllowAsynRequest"/>
	</message>
	<portType name="ExportAllowCallbackType">
		<operation name="callback">
			<input message="y:ExportAllowCallbackInputMessage"/>
		</operation>
	</portType>
	<binding name="ExportAllowCallbackBinding" type="y:ExportAllowCallbackType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="callback">
			<soap:operation/>
			<input>
				<soap:body use="literal"/>
			</input>
		</operation>
	</binding>
	<service name="ExportAllowAsynCallbackService">
		<port name="ExportAllowAsynCallbackPort" binding="y:ExportAllowCallbackBinding">
			<soap:address location="No Target Adress"/>
		</port>
	</service>
</definitions>
