<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2005 sp2 U (http://www.altova.com) by  () -->
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:y="http://JSTV/PublicService/ImportAllowService/" xmlns:ns="http://JSTV/PublicService/Parameter/" targetNamespace="http://JSTV/PublicService/ImportAllowService/">
	<types>
		<xs:schema xmlns:ns1="http://JSTV/PublicService/Parameter/">
			<xs:import namespace="http://JSTV/PublicService/Parameter/" schemaLocation="PublicServiceParameter.xsd"/>
		</xs:schema>
	</types>
	<message name="MetadataImportRequestMessage">
		<part name="MetadataImportRequest" element="ns:ImportRequest"/>
	</message>
	<message name="MetadataImportResponseMessage">
		<part name="MetadataImportResponse" element="ns:ImportResponse"/>
	</message>
	<portType name="MetadataImportType">
		<operation name="Import">
			<input message="y:MetadataImportRequestMessage"/>
			<output message="y:MetadataImportResponseMessage"/>
		</operation>
	</portType>
	<binding name="MatadataImportSoapBinding" type="y:MetadataImportType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="Import">
			<input>
				<soap:body use="literal"/>
			</input>
			<output>
				<soap:body use="literal"/>
			</output>
		</operation>
	</binding>
	<service name="MetadataImportService">
		<port name="MetadataImportPort" binding="y:MatadataImportSoapBinding">
			<soap:address location="No Target Adress"/>
		</port>
	</service>
</definitions>
