//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4952
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://CMMB/schema/DataTypes", ClrNamespace="cmmb.schema.DataTypes")]



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://CMMB.ESBService.namespace", ConfigurationName="DeviceInterface")]
public interface DeviceInterface
{
    
    // CODEGEN: 操作 GetDeviceTypes 以后生成的消息协定不是 RPC，也不是换行文档。
    [System.ServiceModel.OperationContractAttribute(Action="GetDeviceTypes", ReplyAction="*")]
    [System.ServiceModel.FaultContractAttribute(typeof(cmmb.schema.DataTypes.FaultMessage), Action="GetDeviceTypes", Name="FaultMessage", Namespace="http://CMMB/schema/DataTypes")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MonitorObjTopologyType))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DeviceTopologyType))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MaintenanceDataType))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DeviceInfoType))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StuffInfoType))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MonitorObjType))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataVersionType))]
    GetDeviceTypesResponse GetDeviceTypes(GetDeviceTypesRequest request);
    
    // CODEGEN: 操作 GetDeviceParameterDefinition 以后生成的消息协定不是 RPC，也不是换行文档。
    [System.ServiceModel.OperationContractAttribute(Action="GetDeviceParameterDefinition", ReplyAction="*")]
    [System.ServiceModel.FaultContractAttribute(typeof(cmmb.schema.DataTypes.FaultMessage), Action="GetDeviceParameterDefinition", Name="FaultMessage", Namespace="http://CMMB/schema/DataTypes")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MonitorObjTopologyType))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DeviceTopologyType))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MaintenanceDataType))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DeviceInfoType))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StuffInfoType))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MonitorObjType))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataVersionType))]
    GetDeviceParameterDefinitionResponse GetDeviceParameterDefinition(GetDeviceParameterDefinitionRequest request);
    
    // CODEGEN: 操作 NotifyDataInfo 以后生成的消息协定不是 RPC，也不是换行文档。
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="NotifyDataInfo")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MonitorObjTopologyType))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DeviceTopologyType))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MaintenanceDataType))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DeviceInfoType))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StuffInfoType))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MonitorObjType))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataVersionType))]
    void NotifyDataInfo(NotifyDataInfo request);
    
    // CODEGEN: 操作 GetManufacturerInfo 以后生成的消息协定不是 RPC，也不是换行文档。
    [System.ServiceModel.OperationContractAttribute(Action="GetManufacturerInfo", ReplyAction="*")]
    [System.ServiceModel.FaultContractAttribute(typeof(cmmb.schema.DataTypes.FaultMessage), Action="GetManufacturerInfo", Name="FaultMessage", Namespace="http://CMMB/schema/DataTypes")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MonitorObjTopologyType))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DeviceTopologyType))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MaintenanceDataType))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DeviceInfoType))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StuffInfoType))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MonitorObjType))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataVersionType))]
    GetManufacturerInfoResponse GetManufacturerInfo(GetManufacturerInfoRequest request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://CMMB/schema/DataTypes")]
public partial class RequestHead
{
    
    private string sourceSysIDField;
    
    private string targetSysIDField;
    
    private string targetServiceNameField;
    
    private System.DateTime timeStampField;
    
    private int dataTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string SourceSysID
    {
        get
        {
            return this.sourceSysIDField;
        }
        set
        {
            this.sourceSysIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string TargetSysID
    {
        get
        {
            return this.targetSysIDField;
        }
        set
        {
            this.targetSysIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string TargetServiceName
    {
        get
        {
            return this.targetServiceNameField;
        }
        set
        {
            this.targetServiceNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public System.DateTime TimeStamp
    {
        get
        {
            return this.timeStampField;
        }
        set
        {
            this.timeStampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public int DataType
    {
        get
        {
            return this.dataTypeField;
        }
        set
        {
            this.dataTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://CMMB/schema/DataTypes")]
public partial class MonitorObjTopologyType
{
    
    private MonitorObjNodeType[] monitorObjNodesField;
    
    private LinkType[] linksField;
    
    private byte[] mapImageField;
    
    private string idField;
    
    private string nameField;
    
    private string monitorObjCodeField;
    
    private string descField;
    
    private double widthField;
    
    private double heightField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MonitorObjNodes", Order=0)]
    public MonitorObjNodeType[] MonitorObjNodes
    {
        get
        {
            return this.monitorObjNodesField;
        }
        set
        {
            this.monitorObjNodesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Links", Order=1)]
    public LinkType[] Links
    {
        get
        {
            return this.linksField;
        }
        set
        {
            this.linksField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=2)]
    public byte[] MapImage
    {
        get
        {
            return this.mapImageField;
        }
        set
        {
            this.mapImageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ID
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MonitorObjCode
    {
        get
        {
            return this.monitorObjCodeField;
        }
        set
        {
            this.monitorObjCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Desc
    {
        get
        {
            return this.descField;
        }
        set
        {
            this.descField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double Width
    {
        get
        {
            return this.widthField;
        }
        set
        {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double Height
    {
        get
        {
            return this.heightField;
        }
        set
        {
            this.heightField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://CMMB/schema/DataTypes")]
public partial class MonitorObjNodeType
{
    
    private string idField;
    
    private string monitorObjCodeField;
    
    private string nameField;
    
    private string descField;
    
    private double heightField;
    
    private double widthField;
    
    private double locationXField;
    
    private double locationYField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ID
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MonitorObjCode
    {
        get
        {
            return this.monitorObjCodeField;
        }
        set
        {
            this.monitorObjCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Desc
    {
        get
        {
            return this.descField;
        }
        set
        {
            this.descField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double Height
    {
        get
        {
            return this.heightField;
        }
        set
        {
            this.heightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double Width
    {
        get
        {
            return this.widthField;
        }
        set
        {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double LocationX
    {
        get
        {
            return this.locationXField;
        }
        set
        {
            this.locationXField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double LocationY
    {
        get
        {
            return this.locationYField;
        }
        set
        {
            this.locationYField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://CMMB/schema/DataTypes")]
public partial class LinkType
{
    
    private string idField;
    
    private string nameField;
    
    private string fromNodeIDField;
    
    private string toNodeIDField;
    
    private LinkTypeArrowDirection arrowDirectionField;
    
    private string fromPortNameField;
    
    private string toPortNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ID
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FromNodeID
    {
        get
        {
            return this.fromNodeIDField;
        }
        set
        {
            this.fromNodeIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ToNodeID
    {
        get
        {
            return this.toNodeIDField;
        }
        set
        {
            this.toNodeIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public LinkTypeArrowDirection ArrowDirection
    {
        get
        {
            return this.arrowDirectionField;
        }
        set
        {
            this.arrowDirectionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FromPortName
    {
        get
        {
            return this.fromPortNameField;
        }
        set
        {
            this.fromPortNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ToPortName
    {
        get
        {
            return this.toPortNameField;
        }
        set
        {
            this.toPortNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://CMMB/schema/DataTypes")]
public enum LinkTypeArrowDirection
{
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://CMMB/schema/DataTypes")]
public partial class DeviceTopologyType
{
    
    private DeviceNodeType[] nodesField;
    
    private LinkType[] linksField;
    
    private string idField;
    
    private string nameField;
    
    private string monitorObjCodeField;
    
    private string descField;
    
    private double widthField;
    
    private double heightField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Nodes", Order=0)]
    public DeviceNodeType[] Nodes
    {
        get
        {
            return this.nodesField;
        }
        set
        {
            this.nodesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Links", Order=1)]
    public LinkType[] Links
    {
        get
        {
            return this.linksField;
        }
        set
        {
            this.linksField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ID
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MonitorObjCode
    {
        get
        {
            return this.monitorObjCodeField;
        }
        set
        {
            this.monitorObjCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Desc
    {
        get
        {
            return this.descField;
        }
        set
        {
            this.descField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double Width
    {
        get
        {
            return this.widthField;
        }
        set
        {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double Height
    {
        get
        {
            return this.heightField;
        }
        set
        {
            this.heightField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://CMMB/schema/DataTypes")]
public partial class DeviceNodeType
{
    
    private object itemField;
    
    private string idField;
    
    private string parentNodeIDField;
    
    private string nameField;
    
    private string descField;
    
    private double heightField;
    
    private double widthField;
    
    private double locationXField;
    
    private double locationYField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DeviceInfo", typeof(DeviceNodeTypeDeviceInfo), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("GroupInfo", typeof(DeviceNodeTypeGroupInfo), Order=0)]
    public object Item
    {
        get
        {
            return this.itemField;
        }
        set
        {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ID
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ParentNodeID
    {
        get
        {
            return this.parentNodeIDField;
        }
        set
        {
            this.parentNodeIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Desc
    {
        get
        {
            return this.descField;
        }
        set
        {
            this.descField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double Height
    {
        get
        {
            return this.heightField;
        }
        set
        {
            this.heightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double Width
    {
        get
        {
            return this.widthField;
        }
        set
        {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double LocationX
    {
        get
        {
            return this.locationXField;
        }
        set
        {
            this.locationXField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double LocationY
    {
        get
        {
            return this.locationYField;
        }
        set
        {
            this.locationYField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://CMMB/schema/DataTypes")]
public partial class DeviceNodeTypeDeviceInfo
{
    
    private string deviceCodeField;
    
    private string deviceTypeCodeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DeviceCode
    {
        get
        {
            return this.deviceCodeField;
        }
        set
        {
            this.deviceCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DeviceTypeCode
    {
        get
        {
            return this.deviceTypeCodeField;
        }
        set
        {
            this.deviceTypeCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://CMMB/schema/DataTypes")]
public partial class DeviceNodeTypeGroupInfo
{
    
    private string backgroundImgIDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string BackgroundImgID
    {
        get
        {
            return this.backgroundImgIDField;
        }
        set
        {
            this.backgroundImgIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://CMMB/schema/DataTypes")]
public partial class MTADataExtenableDefType
{
    
    private string[] msgFunctionClassEnumField;
    
    private string[] msgLevelEnumField;
    
    private string[] msgModeEnumField;
    
    private object msgParam1SchemaField;
    
    private object msgParam2SchemaField;
    
    private string[] transactionTypeEnumField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
    [System.Xml.Serialization.XmlArrayItemAttribute("EnumEntity", IsNullable=false)]
    public string[] MsgFunctionClassEnum
    {
        get
        {
            return this.msgFunctionClassEnumField;
        }
        set
        {
            this.msgFunctionClassEnumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
    [System.Xml.Serialization.XmlArrayItemAttribute("EnumEntity", IsNullable=false)]
    public string[] MsgLevelEnum
    {
        get
        {
            return this.msgLevelEnumField;
        }
        set
        {
            this.msgLevelEnumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
    [System.Xml.Serialization.XmlArrayItemAttribute("EnumEntity", IsNullable=false)]
    public string[] MsgModeEnum
    {
        get
        {
            return this.msgModeEnumField;
        }
        set
        {
            this.msgModeEnumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public object MsgParam1Schema
    {
        get
        {
            return this.msgParam1SchemaField;
        }
        set
        {
            this.msgParam1SchemaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public object MsgParam2Schema
    {
        get
        {
            return this.msgParam2SchemaField;
        }
        set
        {
            this.msgParam2SchemaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
    [System.Xml.Serialization.XmlArrayItemAttribute("EnumEntity", IsNullable=false)]
    public string[] TransactionTypeEnum
    {
        get
        {
            return this.transactionTypeEnumField;
        }
        set
        {
            this.transactionTypeEnumField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://CMMB/schema/DataTypes")]
public partial class ManufacturerInfoType
{
    
    private object manufacturerCodeField;
    
    private object manufacturerNameField;
    
    private object manufacturerLinkManField;
    
    private object manufacturerLinkPhoneField;
    
    private object manufacturerAddressField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public object ManufacturerCode
    {
        get
        {
            return this.manufacturerCodeField;
        }
        set
        {
            this.manufacturerCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public object ManufacturerName
    {
        get
        {
            return this.manufacturerNameField;
        }
        set
        {
            this.manufacturerNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public object ManufacturerLinkMan
    {
        get
        {
            return this.manufacturerLinkManField;
        }
        set
        {
            this.manufacturerLinkManField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public object ManufacturerLinkPhone
    {
        get
        {
            return this.manufacturerLinkPhoneField;
        }
        set
        {
            this.manufacturerLinkPhoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public object ManufacturerAddress
    {
        get
        {
            return this.manufacturerAddressField;
        }
        set
        {
            this.manufacturerAddressField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://CMMB/schema/DataTypes")]
public partial class MessageDataType
{
    
    private object param1Field;
    
    private object param2Field;
    
    private string[] modesField;
    
    private string contentField;
    
    private MessageDataTypeAttachment[] attachmentField;
    
    private string gUIDField;
    
    private string monitorObjCodeField;
    
    private string stuffCodeField;
    
    private System.DateTime timeField;
    
    private string functionalClassField;
    
    private string levelField;
    
    private MessageDataTypeNeedReceipt needReceiptField;
    
    private MessageDataTypeRange rangeField;
    
    private string titleField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public object Param1
    {
        get
        {
            return this.param1Field;
        }
        set
        {
            this.param1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public object Param2
    {
        get
        {
            return this.param2Field;
        }
        set
        {
            this.param2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Mode", IsNullable=false)]
    public string[] Modes
    {
        get
        {
            return this.modesField;
        }
        set
        {
            this.modesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string Content
    {
        get
        {
            return this.contentField;
        }
        set
        {
            this.contentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Attachment", Order=4)]
    public MessageDataTypeAttachment[] Attachment
    {
        get
        {
            return this.attachmentField;
        }
        set
        {
            this.attachmentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string GUID
    {
        get
        {
            return this.gUIDField;
        }
        set
        {
            this.gUIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MonitorObjCode
    {
        get
        {
            return this.monitorObjCodeField;
        }
        set
        {
            this.monitorObjCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string StuffCode
    {
        get
        {
            return this.stuffCodeField;
        }
        set
        {
            this.stuffCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime Time
    {
        get
        {
            return this.timeField;
        }
        set
        {
            this.timeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FunctionalClass
    {
        get
        {
            return this.functionalClassField;
        }
        set
        {
            this.functionalClassField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Level
    {
        get
        {
            return this.levelField;
        }
        set
        {
            this.levelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public MessageDataTypeNeedReceipt NeedReceipt
    {
        get
        {
            return this.needReceiptField;
        }
        set
        {
            this.needReceiptField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public MessageDataTypeRange Range
    {
        get
        {
            return this.rangeField;
        }
        set
        {
            this.rangeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Title
    {
        get
        {
            return this.titleField;
        }
        set
        {
            this.titleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://CMMB/schema/DataTypes")]
public partial class MessageDataTypeAttachment
{
    
    private string nameField;
    
    private byte[] valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
    public byte[] Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://CMMB/schema/DataTypes")]
public enum MessageDataTypeNeedReceipt
{
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://CMMB/schema/DataTypes")]
public enum MessageDataTypeRange
{
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://CMMB/schema/DataTypes")]
public partial class MaintenanceDataType
{
    
    private string stuffCodeField;
    
    private string monitorObjCodeField;
    
    private System.DateTime timeField;
    
    private string transactionTypeField;
    
    private string summaryField;
    
    private object miscellaneousField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string StuffCode
    {
        get
        {
            return this.stuffCodeField;
        }
        set
        {
            this.stuffCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string MonitorObjCode
    {
        get
        {
            return this.monitorObjCodeField;
        }
        set
        {
            this.monitorObjCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public System.DateTime Time
    {
        get
        {
            return this.timeField;
        }
        set
        {
            this.timeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string TransactionType
    {
        get
        {
            return this.transactionTypeField;
        }
        set
        {
            this.transactionTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public string Summary
    {
        get
        {
            return this.summaryField;
        }
        set
        {
            this.summaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public object Miscellaneous
    {
        get
        {
            return this.miscellaneousField;
        }
        set
        {
            this.miscellaneousField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://CMMB/schema/DataTypes")]
public partial class DeviceInfoType
{
    
    private string deviceCodeField;
    
    private string monitorObjCodeField;
    
    private string deviceNameField;
    
    private string deviceTypeCodeField;
    
    private string manufacturerCodeField;
    
    private System.DateTime entryTimeField;
    
    private System.DateTime abandonTimeField;
    
    private bool abandonTimeFieldSpecified;
    
    private DeviceInfoTypeStatus statusField;
    
    private string remarkField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DeviceCode
    {
        get
        {
            return this.deviceCodeField;
        }
        set
        {
            this.deviceCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MonitorObjCode
    {
        get
        {
            return this.monitorObjCodeField;
        }
        set
        {
            this.monitorObjCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DeviceName
    {
        get
        {
            return this.deviceNameField;
        }
        set
        {
            this.deviceNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DeviceTypeCode
    {
        get
        {
            return this.deviceTypeCodeField;
        }
        set
        {
            this.deviceTypeCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ManufacturerCode
    {
        get
        {
            return this.manufacturerCodeField;
        }
        set
        {
            this.manufacturerCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime EntryTime
    {
        get
        {
            return this.entryTimeField;
        }
        set
        {
            this.entryTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime AbandonTime
    {
        get
        {
            return this.abandonTimeField;
        }
        set
        {
            this.abandonTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AbandonTimeSpecified
    {
        get
        {
            return this.abandonTimeFieldSpecified;
        }
        set
        {
            this.abandonTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public DeviceInfoTypeStatus Status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Remark
    {
        get
        {
            return this.remarkField;
        }
        set
        {
            this.remarkField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://CMMB/schema/DataTypes")]
public enum DeviceInfoTypeStatus
{
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://CMMB/schema/DataTypes")]
public partial class StuffInfoType
{
    
    private string stuffCodeField;
    
    private string monitorObjCodeField;
    
    private string entryIDField;
    
    private string nameField;
    
    private string positionField;
    
    private string telephone1Field;
    
    private string telephone2Field;
    
    private StuffInfoTypeStatus statusField;
    
    private string eMailField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string StuffCode
    {
        get
        {
            return this.stuffCodeField;
        }
        set
        {
            this.stuffCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MonitorObjCode
    {
        get
        {
            return this.monitorObjCodeField;
        }
        set
        {
            this.monitorObjCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string EntryID
    {
        get
        {
            return this.entryIDField;
        }
        set
        {
            this.entryIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Position
    {
        get
        {
            return this.positionField;
        }
        set
        {
            this.positionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Telephone1
    {
        get
        {
            return this.telephone1Field;
        }
        set
        {
            this.telephone1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Telephone2
    {
        get
        {
            return this.telephone2Field;
        }
        set
        {
            this.telephone2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public StuffInfoTypeStatus Status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("E-Mail")]
    public string EMail
    {
        get
        {
            return this.eMailField;
        }
        set
        {
            this.eMailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://CMMB/schema/DataTypes")]
public enum StuffInfoTypeStatus
{
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://CMMB/schema/DataTypes")]
public partial class MonitorObjType
{
    
    private MonitorObjType[] childNodesField;
    
    private string monitorObjCodeField;
    
    private string nameField;
    
    private string parentObjCodeField;
    
    private MonitorObjTypeType typeField;
    
    private int plateformLevelField;
    
    private string principalCodeField;
    
    private string dutyTelephoneNumberField;
    
    private string ipField;
    
    private int portField;
    
    private bool portFieldSpecified;
    
    private decimal longitudeField;
    
    private bool longitudeFieldSpecified;
    
    private decimal latitudeField;
    
    private bool latitudeFieldSpecified;
    
    private MonitorObjTypeStatus statusField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ChildNodes", Order=0)]
    public MonitorObjType[] ChildNodes
    {
        get
        {
            return this.childNodesField;
        }
        set
        {
            this.childNodesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MonitorObjCode
    {
        get
        {
            return this.monitorObjCodeField;
        }
        set
        {
            this.monitorObjCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ParentObjCode
    {
        get
        {
            return this.parentObjCodeField;
        }
        set
        {
            this.parentObjCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public MonitorObjTypeType Type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int PlateformLevel
    {
        get
        {
            return this.plateformLevelField;
        }
        set
        {
            this.plateformLevelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PrincipalCode
    {
        get
        {
            return this.principalCodeField;
        }
        set
        {
            this.principalCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DutyTelephoneNumber
    {
        get
        {
            return this.dutyTelephoneNumberField;
        }
        set
        {
            this.dutyTelephoneNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string IP
    {
        get
        {
            return this.ipField;
        }
        set
        {
            this.ipField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int Port
    {
        get
        {
            return this.portField;
        }
        set
        {
            this.portField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PortSpecified
    {
        get
        {
            return this.portFieldSpecified;
        }
        set
        {
            this.portFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal Longitude
    {
        get
        {
            return this.longitudeField;
        }
        set
        {
            this.longitudeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LongitudeSpecified
    {
        get
        {
            return this.longitudeFieldSpecified;
        }
        set
        {
            this.longitudeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal Latitude
    {
        get
        {
            return this.latitudeField;
        }
        set
        {
            this.latitudeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LatitudeSpecified
    {
        get
        {
            return this.latitudeFieldSpecified;
        }
        set
        {
            this.latitudeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public MonitorObjTypeStatus Status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://CMMB/schema/DataTypes")]
public enum MonitorObjTypeType
{
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("4")]
    Item4,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("5")]
    Item5,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://CMMB/schema/DataTypes")]
public enum MonitorObjTypeStatus
{
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://CMMB/schema/DataTypes")]
public partial class DataVersionType
{
    
    private string monitorObjCodeField;
    
    private string versionCodeField;
    
    private string descriptionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MonitorObjCode
    {
        get
        {
            return this.monitorObjCodeField;
        }
        set
        {
            this.monitorObjCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string VersionCode
    {
        get
        {
            return this.versionCodeField;
        }
        set
        {
            this.versionCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://CMMB/schema/DataTypes")]
public partial class ProductionDataType
{
    
    private string monitorObjCodeField;
    
    private string deviceCodeField;
    
    private string parameterCodeField;
    
    private System.DateTime timeField;
    
    private string valueField;
    
    private ParameterStatusType statusField;
    
    private string remarkField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MonitorObjCode
    {
        get
        {
            return this.monitorObjCodeField;
        }
        set
        {
            this.monitorObjCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DeviceCode
    {
        get
        {
            return this.deviceCodeField;
        }
        set
        {
            this.deviceCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ParameterCode
    {
        get
        {
            return this.parameterCodeField;
        }
        set
        {
            this.parameterCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime Time
    {
        get
        {
            return this.timeField;
        }
        set
        {
            this.timeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ParameterStatusType Status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Remark
    {
        get
        {
            return this.remarkField;
        }
        set
        {
            this.remarkField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://CMMB/schema/DataTypes")]
public enum ParameterStatusType
{
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("4")]
    Item4,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://CMMB/schema/DataTypes")]
public partial class ParameterType
{
    
    private string parameterCodeField;
    
    private ParameterTypeParamType paramTypeField;
    
    private int valTypeField;
    
    private bool valTypeFieldSpecified;
    
    private string nameField;
    
    private string deviceTypeCodeField;
    
    private string unitField;
    
    private ParameterTypeUploadType uploadTypeField;
    
    private ParameterTypeLevel levelField;
    
    private string upThresholdField;
    
    private string downThresholdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ParameterCode
    {
        get
        {
            return this.parameterCodeField;
        }
        set
        {
            this.parameterCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ParameterTypeParamType ParamType
    {
        get
        {
            return this.paramTypeField;
        }
        set
        {
            this.paramTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int ValType
    {
        get
        {
            return this.valTypeField;
        }
        set
        {
            this.valTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ValTypeSpecified
    {
        get
        {
            return this.valTypeFieldSpecified;
        }
        set
        {
            this.valTypeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DeviceTypeCode
    {
        get
        {
            return this.deviceTypeCodeField;
        }
        set
        {
            this.deviceTypeCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Unit
    {
        get
        {
            return this.unitField;
        }
        set
        {
            this.unitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ParameterTypeUploadType UploadType
    {
        get
        {
            return this.uploadTypeField;
        }
        set
        {
            this.uploadTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ParameterTypeLevel Level
    {
        get
        {
            return this.levelField;
        }
        set
        {
            this.levelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string UpThreshold
    {
        get
        {
            return this.upThresholdField;
        }
        set
        {
            this.upThresholdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DownThreshold
    {
        get
        {
            return this.downThresholdField;
        }
        set
        {
            this.downThresholdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://CMMB/schema/DataTypes")]
public enum ParameterTypeParamType
{
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://CMMB/schema/DataTypes")]
public enum ParameterTypeUploadType
{
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://CMMB/schema/DataTypes")]
public enum ParameterTypeLevel
{
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://CMMB/schema/DataTypes")]
public partial class DeviceTypeInfo
{
    
    private string deviceTypeCodeField;
    
    private string typeNameField;
    
    private string descField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DeviceTypeCode
    {
        get
        {
            return this.deviceTypeCodeField;
        }
        set
        {
            this.deviceTypeCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TypeName
    {
        get
        {
            return this.typeNameField;
        }
        set
        {
            this.typeNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Desc
    {
        get
        {
            return this.descField;
        }
        set
        {
            this.descField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetDeviceTypesRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CMMB/schema/DataTypes", Order=0)]
    public RequestHead RequestHead;
    
    public GetDeviceTypesRequest()
    {
    }
    
    public GetDeviceTypesRequest(RequestHead RequestHead)
    {
        this.RequestHead = RequestHead;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetDeviceTypesResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CMMB/schema/DataTypes", Order=0)]
    [System.Xml.Serialization.XmlArrayItemAttribute("DeviceTypeInfo", IsNullable=false)]
    public DeviceTypeInfo[] DeviceTypeList;
    
    public GetDeviceTypesResponse()
    {
    }
    
    public GetDeviceTypesResponse(DeviceTypeInfo[] DeviceTypeList)
    {
        this.DeviceTypeList = DeviceTypeList;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://CMMB/schema/DataTypes")]
public partial class DeviceParameterList
{
    
    private ParameterType[] parameterField;
    
    private string deviceTypeCodeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Parameter", Order=0)]
    public ParameterType[] Parameter
    {
        get
        {
            return this.parameterField;
        }
        set
        {
            this.parameterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DeviceTypeCode
    {
        get
        {
            return this.deviceTypeCodeField;
        }
        set
        {
            this.deviceTypeCodeField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetDeviceParameterDefinitionRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CMMB/schema/DataTypes", Order=0)]
    public RequestHead RequestHead;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CMMB/schema/DataTypes", Order=1)]
    public string DeviceTypeCode;
    
    public GetDeviceParameterDefinitionRequest()
    {
    }
    
    public GetDeviceParameterDefinitionRequest(RequestHead RequestHead, string DeviceTypeCode)
    {
        this.RequestHead = RequestHead;
        this.DeviceTypeCode = DeviceTypeCode;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetDeviceParameterDefinitionResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CMMB/schema/DataTypes", Order=0)]
    public DeviceParameterList DeviceParameterList;
    
    public GetDeviceParameterDefinitionResponse()
    {
    }
    
    public GetDeviceParameterDefinitionResponse(DeviceParameterList DeviceParameterList)
    {
        this.DeviceParameterList = DeviceParameterList;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://CMMB/schema/DataTypes")]
public partial class NotifyData
{
    
    private string summaryField;
    
    private ProductionDataType[] dataInfoField;
    
    private object miscellaneousField;
    
    private string monitorObjCodeField;
    
    private System.DateTime timeField;
    
    private string titleField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string Summary
    {
        get
        {
            return this.summaryField;
        }
        set
        {
            this.summaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DataInfo", Order=1)]
    public ProductionDataType[] DataInfo
    {
        get
        {
            return this.dataInfoField;
        }
        set
        {
            this.dataInfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public object Miscellaneous
    {
        get
        {
            return this.miscellaneousField;
        }
        set
        {
            this.miscellaneousField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MonitorObjCode
    {
        get
        {
            return this.monitorObjCodeField;
        }
        set
        {
            this.monitorObjCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime Time
    {
        get
        {
            return this.timeField;
        }
        set
        {
            this.timeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Title
    {
        get
        {
            return this.titleField;
        }
        set
        {
            this.titleField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class NotifyDataInfo
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CMMB/schema/DataTypes", Order=0)]
    public RequestHead RequestHead;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CMMB/schema/DataTypes", Order=1)]
    public NotifyData NotifyData;
    
    public NotifyDataInfo()
    {
    }
    
    public NotifyDataInfo(RequestHead RequestHead, NotifyData NotifyData)
    {
        this.RequestHead = RequestHead;
        this.NotifyData = NotifyData;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetManufacturerInfoRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CMMB/schema/DataTypes", Order=0)]
    public RequestHead RequestHead;
    
    public GetManufacturerInfoRequest()
    {
    }
    
    public GetManufacturerInfoRequest(RequestHead RequestHead)
    {
        this.RequestHead = RequestHead;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetManufacturerInfoResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CMMB/schema/DataTypes", Order=0)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Manufacturer", IsNullable=false)]
    public ManufacturerInfoType[] ManufacturerInfoList;
    
    public GetManufacturerInfoResponse()
    {
    }
    
    public GetManufacturerInfoResponse(ManufacturerInfoType[] ManufacturerInfoList)
    {
        this.ManufacturerInfoList = ManufacturerInfoList;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface DeviceInterfaceChannel : DeviceInterface, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class DeviceInterfaceClient : System.ServiceModel.ClientBase<DeviceInterface>, DeviceInterface
{
    
    public DeviceInterfaceClient()
    {
    }
    
    public DeviceInterfaceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public DeviceInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DeviceInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DeviceInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetDeviceTypesResponse DeviceInterface.GetDeviceTypes(GetDeviceTypesRequest request)
    {
        return base.Channel.GetDeviceTypes(request);
    }
    
    public DeviceTypeInfo[] GetDeviceTypes(RequestHead RequestHead)
    {
        GetDeviceTypesRequest inValue = new GetDeviceTypesRequest();
        inValue.RequestHead = RequestHead;
        GetDeviceTypesResponse retVal = ((DeviceInterface)(this)).GetDeviceTypes(inValue);
        return retVal.DeviceTypeList;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetDeviceParameterDefinitionResponse DeviceInterface.GetDeviceParameterDefinition(GetDeviceParameterDefinitionRequest request)
    {
        return base.Channel.GetDeviceParameterDefinition(request);
    }
    
    public DeviceParameterList GetDeviceParameterDefinition(RequestHead RequestHead, string DeviceTypeCode)
    {
        GetDeviceParameterDefinitionRequest inValue = new GetDeviceParameterDefinitionRequest();
        inValue.RequestHead = RequestHead;
        inValue.DeviceTypeCode = DeviceTypeCode;
        GetDeviceParameterDefinitionResponse retVal = ((DeviceInterface)(this)).GetDeviceParameterDefinition(inValue);
        return retVal.DeviceParameterList;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    void DeviceInterface.NotifyDataInfo(NotifyDataInfo request)
    {
        base.Channel.NotifyDataInfo(request);
    }
    
    public void NotifyDataInfo(RequestHead RequestHead, NotifyData NotifyData)
    {
        NotifyDataInfo inValue = new NotifyDataInfo();
        inValue.RequestHead = RequestHead;
        inValue.NotifyData = NotifyData;
        ((DeviceInterface)(this)).NotifyDataInfo(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetManufacturerInfoResponse DeviceInterface.GetManufacturerInfo(GetManufacturerInfoRequest request)
    {
        return base.Channel.GetManufacturerInfo(request);
    }
    
    public ManufacturerInfoType[] GetManufacturerInfo(RequestHead RequestHead)
    {
        GetManufacturerInfoRequest inValue = new GetManufacturerInfoRequest();
        inValue.RequestHead = RequestHead;
        GetManufacturerInfoResponse retVal = ((DeviceInterface)(this)).GetManufacturerInfo(inValue);
        return retVal.ManufacturerInfoList;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://CMMB.ESBService.namespace", ConfigurationName="MonitorObjInterface")]
public interface MonitorObjInterface
{
    
    // CODEGEN: 操作 GetMonitorObjStatus 以后生成的消息协定不是 RPC，也不是换行文档。
    [System.ServiceModel.OperationContractAttribute(Action="GetMonitorObjStatus", ReplyAction="*")]
    [System.ServiceModel.FaultContractAttribute(typeof(cmmb.schema.DataTypes.FaultMessage), Action="GetMonitorObjStatus", Name="FaultMessage", Namespace="http://CMMB/schema/DataTypes")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MonitorObjTopologyType))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DeviceTopologyType))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MaintenanceDataType))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DeviceInfoType))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StuffInfoType))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MonitorObjType))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataVersionType))]
    GetMonitorObjStatusResponse GetMonitorObjStatus(GetMonitorObjStatusRequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetMonitorObjStatusRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CMMB/schema/DataTypes", Order=0)]
    public RequestHead RequestHead;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CMMB/schema/DataTypes", Order=1)]
    public string MonitorObjCode;
    
    public GetMonitorObjStatusRequest()
    {
    }
    
    public GetMonitorObjStatusRequest(RequestHead RequestHead, string MonitorObjCode)
    {
        this.RequestHead = RequestHead;
        this.MonitorObjCode = MonitorObjCode;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetMonitorObjStatusResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public int response;
    
    public GetMonitorObjStatusResponse()
    {
    }
    
    public GetMonitorObjStatusResponse(int response)
    {
        this.response = response;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface MonitorObjInterfaceChannel : MonitorObjInterface, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class MonitorObjInterfaceClient : System.ServiceModel.ClientBase<MonitorObjInterface>, MonitorObjInterface
{
    
    public MonitorObjInterfaceClient()
    {
    }
    
    public MonitorObjInterfaceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public MonitorObjInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MonitorObjInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MonitorObjInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetMonitorObjStatusResponse MonitorObjInterface.GetMonitorObjStatus(GetMonitorObjStatusRequest request)
    {
        return base.Channel.GetMonitorObjStatus(request);
    }
    
    public int GetMonitorObjStatus(RequestHead RequestHead, string MonitorObjCode)
    {
        GetMonitorObjStatusRequest inValue = new GetMonitorObjStatusRequest();
        inValue.RequestHead = RequestHead;
        inValue.MonitorObjCode = MonitorObjCode;
        GetMonitorObjStatusResponse retVal = ((MonitorObjInterface)(this)).GetMonitorObjStatus(inValue);
        return retVal.response;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://CMMB.ESBService.namespace", ConfigurationName="MaintenanceInterface")]
public interface MaintenanceInterface
{
    
    // CODEGEN: 操作 SendMTAMessage 以后生成的消息协定不是 RPC，也不是换行文档。
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="SendMTAMessage")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MonitorObjTopologyType))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DeviceTopologyType))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MaintenanceDataType))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DeviceInfoType))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StuffInfoType))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MonitorObjType))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataVersionType))]
    void SendMTAMessage(SendMTAMessage request);
    
    // CODEGEN: 操作 GetMTAExtendableDef 以后生成的消息协定不是 RPC，也不是换行文档。
    [System.ServiceModel.OperationContractAttribute(Action="GetMTAExtendableDef", ReplyAction="*")]
    [System.ServiceModel.FaultContractAttribute(typeof(cmmb.schema.DataTypes.FaultMessage), Action="GetMTAExtendableDef", Name="FaultMessage", Namespace="http://CMMB/schema/DataTypes")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MonitorObjTopologyType))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DeviceTopologyType))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MaintenanceDataType))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DeviceInfoType))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StuffInfoType))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MonitorObjType))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataVersionType))]
    GetMTAExtendableDefResponse GetMTAExtendableDef(GetMTAExtendableDefRequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class SendMTAMessage
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CMMB/schema/DataTypes", Order=0)]
    public RequestHead RequestHead;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CMMB/schema/DataTypes", Order=1)]
    public MessageDataType MTAMessageData;
    
    public SendMTAMessage()
    {
    }
    
    public SendMTAMessage(RequestHead RequestHead, MessageDataType MTAMessageData)
    {
        this.RequestHead = RequestHead;
        this.MTAMessageData = MTAMessageData;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetMTAExtendableDefRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CMMB/schema/DataTypes", Order=0)]
    public RequestHead RequestHead;
    
    public GetMTAExtendableDefRequest()
    {
    }
    
    public GetMTAExtendableDefRequest(RequestHead RequestHead)
    {
        this.RequestHead = RequestHead;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetMTAExtendableDefResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CMMB/schema/DataTypes", Order=0)]
    public MTADataExtenableDefType MTADataExtensionDef;
    
    public GetMTAExtendableDefResponse()
    {
    }
    
    public GetMTAExtendableDefResponse(MTADataExtenableDefType MTADataExtensionDef)
    {
        this.MTADataExtensionDef = MTADataExtensionDef;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface MaintenanceInterfaceChannel : MaintenanceInterface, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class MaintenanceInterfaceClient : System.ServiceModel.ClientBase<MaintenanceInterface>, MaintenanceInterface
{
    
    public MaintenanceInterfaceClient()
    {
    }
    
    public MaintenanceInterfaceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public MaintenanceInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MaintenanceInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MaintenanceInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    void MaintenanceInterface.SendMTAMessage(SendMTAMessage request)
    {
        base.Channel.SendMTAMessage(request);
    }
    
    public void SendMTAMessage(RequestHead RequestHead, MessageDataType MTAMessageData)
    {
        SendMTAMessage inValue = new SendMTAMessage();
        inValue.RequestHead = RequestHead;
        inValue.MTAMessageData = MTAMessageData;
        ((MaintenanceInterface)(this)).SendMTAMessage(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetMTAExtendableDefResponse MaintenanceInterface.GetMTAExtendableDef(GetMTAExtendableDefRequest request)
    {
        return base.Channel.GetMTAExtendableDef(request);
    }
    
    public MTADataExtenableDefType GetMTAExtendableDef(RequestHead RequestHead)
    {
        GetMTAExtendableDefRequest inValue = new GetMTAExtendableDefRequest();
        inValue.RequestHead = RequestHead;
        GetMTAExtendableDefResponse retVal = ((MaintenanceInterface)(this)).GetMTAExtendableDef(inValue);
        return retVal.MTADataExtensionDef;
    }
}
namespace cmmb.schema.DataTypes
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultMessage", Namespace="http://CMMB/schema/DataTypes")]
    public partial class FaultMessage : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int FaultCodeField;
        
        private string FaultDescField;
        
        private string FaultReasonField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int FaultCode
        {
            get
            {
                return this.FaultCodeField;
            }
            set
            {
                this.FaultCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string FaultDesc
        {
            get
            {
                return this.FaultDescField;
            }
            set
            {
                this.FaultDescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string FaultReason
        {
            get
            {
                return this.FaultReasonField;
            }
            set
            {
                this.FaultReasonField = value;
            }
        }
    }
}
