//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://CMMB.ESBService.namespace", ClrNamespace="cmmb.esbservice.namespace")]



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://CMMB.ESBService.namespace", ConfigurationName="DeviceInterface")]
public interface DeviceInterface
{
    
    // CODEGEN: 操作 getDeviceTypes 以后生成的消息协定不是 RPC，也不是换行文档。
    [System.ServiceModel.OperationContractAttribute(Action="getDeviceTypes")]
    [System.ServiceModel.FaultContractAttribute(typeof(cmmb.esbservice.@namespace.faultMessage), Action="getDeviceTypes", Name="faultMessage")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    getDeviceTypesResponse getDeviceTypes(getDeviceTypesRequest request);
    
    // CODEGEN: 操作 getDeviceParameterDefinition 以后生成的消息协定不是 RPC，也不是换行文档。
    [System.ServiceModel.OperationContractAttribute(Action="getDeviceParameterDefinition")]
    [System.ServiceModel.FaultContractAttribute(typeof(cmmb.esbservice.@namespace.faultMessage), Action="getDeviceParameterDefinition", Name="faultMessage")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    getDeviceParameterDefinitionResponse getDeviceParameterDefinition(getDeviceParameterDefinitionRequest request);
    
    // CODEGEN: 操作 notifyDataInfo 以后生成的消息协定不是 RPC，也不是换行文档。
    [System.ServiceModel.OperationContractAttribute(Action="notifyDataInfo")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    notifyDataInfoResponse notifyDataInfo(notifyDataInfoRequest request);
    
    // CODEGEN: 操作 getManufacturerInfo 以后生成的消息协定不是 RPC，也不是换行文档。
    [System.ServiceModel.OperationContractAttribute(Action="getManufacturerInfo")]
    [System.ServiceModel.FaultContractAttribute(typeof(cmmb.esbservice.@namespace.faultMessage), Action="getManufacturerInfo", Name="faultMessage")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    getManufacturerInfoResponse getManufacturerInfo(getManufacturerInfoRequest request);
    
    // CODEGEN: 操作 notifyUploadEvent 以后生成的消息协定不是 RPC，也不是换行文档。
    [System.ServiceModel.OperationContractAttribute(Action="notifyUploadEvent")]
    [System.ServiceModel.FaultContractAttribute(typeof(cmmb.esbservice.@namespace.faultMessage), Action="notifyUploadEvent", Name="faultMessage")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    notifyUploadEventResponse notifyUploadEvent(notifyUploadEventRequest request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://CMMB.ESBService.namespace")]
public partial class requestHead
{
    
    private string sourceSysIDField;
    
    private string targetSysIDField;
    
    private string targetServiceNameField;
    
    private System.DateTime timeStampField;
    
    private int dataTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string sourceSysID
    {
        get
        {
            return this.sourceSysIDField;
        }
        set
        {
            this.sourceSysIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string targetSysID
    {
        get
        {
            return this.targetSysIDField;
        }
        set
        {
            this.targetSysIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string targetServiceName
    {
        get
        {
            return this.targetServiceNameField;
        }
        set
        {
            this.targetServiceNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public System.DateTime timeStamp
    {
        get
        {
            return this.timeStampField;
        }
        set
        {
            this.timeStampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public int dataType
    {
        get
        {
            return this.dataTypeField;
        }
        set
        {
            this.dataTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://CMMB.ESBService.namespace")]
public partial class mtaDataExtenableDefType
{
    
    private string[] msgFunctionClassEnumField;
    
    private string[] msgLevelEnumField;
    
    private string[] msgModeEnumField;
    
    private object msgParam1SchemaField;
    
    private object msgParam2SchemaField;
    
    private string[] transactionTypeEnumField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
    [System.Xml.Serialization.XmlArrayItemAttribute("enumEntity", IsNullable=false)]
    public string[] msgFunctionClassEnum
    {
        get
        {
            return this.msgFunctionClassEnumField;
        }
        set
        {
            this.msgFunctionClassEnumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
    [System.Xml.Serialization.XmlArrayItemAttribute("enumEntity", IsNullable=false)]
    public string[] msgLevelEnum
    {
        get
        {
            return this.msgLevelEnumField;
        }
        set
        {
            this.msgLevelEnumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
    [System.Xml.Serialization.XmlArrayItemAttribute("enumEntity", IsNullable=false)]
    public string[] msgModeEnum
    {
        get
        {
            return this.msgModeEnumField;
        }
        set
        {
            this.msgModeEnumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public object msgParam1Schema
    {
        get
        {
            return this.msgParam1SchemaField;
        }
        set
        {
            this.msgParam1SchemaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public object msgParam2Schema
    {
        get
        {
            return this.msgParam2SchemaField;
        }
        set
        {
            this.msgParam2SchemaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
    [System.Xml.Serialization.XmlArrayItemAttribute("enumEntity", IsNullable=false)]
    public string[] transactionTypeEnum
    {
        get
        {
            return this.transactionTypeEnumField;
        }
        set
        {
            this.transactionTypeEnumField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://CMMB.ESBService.namespace")]
public partial class manufacturerInfoType
{
    
    private string manufacturerCodeField;
    
    private string manufacturerNameField;
    
    private string manufacturerLinkManField;
    
    private string manufacturerLinkPhoneField;
    
    private string manufacturerAddressField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string manufacturerCode
    {
        get
        {
            return this.manufacturerCodeField;
        }
        set
        {
            this.manufacturerCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string manufacturerName
    {
        get
        {
            return this.manufacturerNameField;
        }
        set
        {
            this.manufacturerNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string manufacturerLinkMan
    {
        get
        {
            return this.manufacturerLinkManField;
        }
        set
        {
            this.manufacturerLinkManField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string manufacturerLinkPhone
    {
        get
        {
            return this.manufacturerLinkPhoneField;
        }
        set
        {
            this.manufacturerLinkPhoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public string manufacturerAddress
    {
        get
        {
            return this.manufacturerAddressField;
        }
        set
        {
            this.manufacturerAddressField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://CMMB.ESBService.namespace")]
public partial class messageDataType
{
    
    private object param1Field;
    
    private object param2Field;
    
    private string[] modesField;
    
    private string contentField;
    
    private messageDataTypeAttachment[] attachmentField;
    
    private string guidField;
    
    private string monitorObjCodeField;
    
    private string stuffCodeField;
    
    private System.DateTime timeField;
    
    private string functionalClassField;
    
    private string levelField;
    
    private int needReceiptField;
    
    private int rangeField;
    
    private string titleField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public object param1
    {
        get
        {
            return this.param1Field;
        }
        set
        {
            this.param1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public object param2
    {
        get
        {
            return this.param2Field;
        }
        set
        {
            this.param2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Mode", IsNullable=false)]
    public string[] modes
    {
        get
        {
            return this.modesField;
        }
        set
        {
            this.modesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string content
    {
        get
        {
            return this.contentField;
        }
        set
        {
            this.contentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("attachment", Order=4)]
    public messageDataTypeAttachment[] attachment
    {
        get
        {
            return this.attachmentField;
        }
        set
        {
            this.attachmentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public string guid
    {
        get
        {
            return this.guidField;
        }
        set
        {
            this.guidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public string monitorObjCode
    {
        get
        {
            return this.monitorObjCodeField;
        }
        set
        {
            this.monitorObjCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public string stuffCode
    {
        get
        {
            return this.stuffCodeField;
        }
        set
        {
            this.stuffCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public System.DateTime time
    {
        get
        {
            return this.timeField;
        }
        set
        {
            this.timeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public string functionalClass
    {
        get
        {
            return this.functionalClassField;
        }
        set
        {
            this.functionalClassField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public string level
    {
        get
        {
            return this.levelField;
        }
        set
        {
            this.levelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public int needReceipt
    {
        get
        {
            return this.needReceiptField;
        }
        set
        {
            this.needReceiptField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public int range
    {
        get
        {
            return this.rangeField;
        }
        set
        {
            this.rangeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public string title
    {
        get
        {
            return this.titleField;
        }
        set
        {
            this.titleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://CMMB.ESBService.namespace")]
public partial class messageDataTypeAttachment
{
    
    private string nameField;
    
    private string ftpURLField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string ftpURL
    {
        get
        {
            return this.ftpURLField;
        }
        set
        {
            this.ftpURLField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://CMMB.ESBService.namespace")]
public partial class productionDataType
{
    
    private int monitorObjCodeField;
    
    private string deviceCodeField;
    
    private string parameterCodeField;
    
    private System.DateTime timeField;
    
    private string valueField;
    
    private int statusField;
    
    private string remarkField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public int monitorObjCode
    {
        get
        {
            return this.monitorObjCodeField;
        }
        set
        {
            this.monitorObjCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public string deviceCode
    {
        get
        {
            return this.deviceCodeField;
        }
        set
        {
            this.deviceCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public string parameterCode
    {
        get
        {
            return this.parameterCodeField;
        }
        set
        {
            this.parameterCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public System.DateTime time
    {
        get
        {
            return this.timeField;
        }
        set
        {
            this.timeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public string value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public int status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public string remark
    {
        get
        {
            return this.remarkField;
        }
        set
        {
            this.remarkField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://CMMB.ESBService.namespace")]
public partial class parameterType
{
    
    private double alarmUpThresholdField;
    
    private bool alarmUpThresholdFieldSpecified;
    
    private double alarmDownThresholdField;
    
    private bool alarmDownThresholdFieldSpecified;
    
    private string[] enumrationField;
    
    private string parameterCodeField;
    
    private int paramTypeField;
    
    private int valTypeField;
    
    private string nameField;
    
    private string deviceTypeCodeField;
    
    private string unitField;
    
    private int uploadTypeField;
    
    private int levelField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public double alarmUpThreshold
    {
        get
        {
            return this.alarmUpThresholdField;
        }
        set
        {
            this.alarmUpThresholdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool alarmUpThresholdSpecified
    {
        get
        {
            return this.alarmUpThresholdFieldSpecified;
        }
        set
        {
            this.alarmUpThresholdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public double alarmDownThreshold
    {
        get
        {
            return this.alarmDownThresholdField;
        }
        set
        {
            this.alarmDownThresholdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool alarmDownThresholdSpecified
    {
        get
        {
            return this.alarmDownThresholdFieldSpecified;
        }
        set
        {
            this.alarmDownThresholdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
    [System.Xml.Serialization.XmlArrayItemAttribute("enumItem", IsNullable=false)]
    public string[] enumration
    {
        get
        {
            return this.enumrationField;
        }
        set
        {
            this.enumrationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public string parameterCode
    {
        get
        {
            return this.parameterCodeField;
        }
        set
        {
            this.parameterCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public int paramType
    {
        get
        {
            return this.paramTypeField;
        }
        set
        {
            this.paramTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public int valType
    {
        get
        {
            return this.valTypeField;
        }
        set
        {
            this.valTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public string deviceTypeCode
    {
        get
        {
            return this.deviceTypeCodeField;
        }
        set
        {
            this.deviceTypeCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public string unit
    {
        get
        {
            return this.unitField;
        }
        set
        {
            this.unitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public int uploadType
    {
        get
        {
            return this.uploadTypeField;
        }
        set
        {
            this.uploadTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public int level
    {
        get
        {
            return this.levelField;
        }
        set
        {
            this.levelField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://CMMB.ESBService.namespace")]
public partial class deviceTypeInfo
{
    
    private string deviceTypeCodeField;
    
    private string typeNameField;
    
    private string descField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public string deviceTypeCode
    {
        get
        {
            return this.deviceTypeCodeField;
        }
        set
        {
            this.deviceTypeCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public string typeName
    {
        get
        {
            return this.typeNameField;
        }
        set
        {
            this.typeNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public string desc
    {
        get
        {
            return this.descField;
        }
        set
        {
            this.descField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getDeviceTypesRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CMMB.ESBService.namespace", Order=0)]
    public requestHead requestHead;
    
    public getDeviceTypesRequest()
    {
    }
    
    public getDeviceTypesRequest(requestHead requestHead)
    {
        this.requestHead = requestHead;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getDeviceTypesResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CMMB.ESBService.namespace", Order=0)]
    [System.Xml.Serialization.XmlArrayItemAttribute("deviceTypeInfo", IsNullable=false)]
    public deviceTypeInfo[] deviceTypeList;
    
    public getDeviceTypesResponse()
    {
    }
    
    public getDeviceTypesResponse(deviceTypeInfo[] deviceTypeList)
    {
        this.deviceTypeList = deviceTypeList;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://CMMB.ESBService.namespace")]
public partial class deviceParameterList
{
    
    private parameterType[] parameterField;
    
    private string deviceTypeCodeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("parameter", Order=0)]
    public parameterType[] parameter
    {
        get
        {
            return this.parameterField;
        }
        set
        {
            this.parameterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public string deviceTypeCode
    {
        get
        {
            return this.deviceTypeCodeField;
        }
        set
        {
            this.deviceTypeCodeField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getDeviceParameterDefinitionRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CMMB.ESBService.namespace", Order=0)]
    public requestHead requestHead;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CMMB.ESBService.namespace", Order=1)]
    public string deviceTypeCode;
    
    public getDeviceParameterDefinitionRequest()
    {
    }
    
    public getDeviceParameterDefinitionRequest(requestHead requestHead, string deviceTypeCode)
    {
        this.requestHead = requestHead;
        this.deviceTypeCode = deviceTypeCode;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getDeviceParameterDefinitionResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CMMB.ESBService.namespace", Order=0)]
    public deviceParameterList deviceParameterList;
    
    public getDeviceParameterDefinitionResponse()
    {
    }
    
    public getDeviceParameterDefinitionResponse(deviceParameterList deviceParameterList)
    {
        this.deviceParameterList = deviceParameterList;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://CMMB.ESBService.namespace")]
public partial class notifyData
{
    
    private string summaryField;
    
    private productionDataType[] dataInfoField;
    
    private object miscellaneousField;
    
    private string monitorObjCodeField;
    
    private System.DateTime timeField;
    
    private string titleField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string summary
    {
        get
        {
            return this.summaryField;
        }
        set
        {
            this.summaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("dataInfo", Order=1)]
    public productionDataType[] dataInfo
    {
        get
        {
            return this.dataInfoField;
        }
        set
        {
            this.dataInfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public object miscellaneous
    {
        get
        {
            return this.miscellaneousField;
        }
        set
        {
            this.miscellaneousField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public string monitorObjCode
    {
        get
        {
            return this.monitorObjCodeField;
        }
        set
        {
            this.monitorObjCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public System.DateTime time
    {
        get
        {
            return this.timeField;
        }
        set
        {
            this.timeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
    public string title
    {
        get
        {
            return this.titleField;
        }
        set
        {
            this.titleField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class notifyDataInfoRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CMMB.ESBService.namespace", Order=0)]
    public requestHead requestHead;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CMMB.ESBService.namespace", Order=1)]
    public notifyData notifyData;
    
    public notifyDataInfoRequest()
    {
    }
    
    public notifyDataInfoRequest(requestHead requestHead, notifyData notifyData)
    {
        this.requestHead = requestHead;
        this.notifyData = notifyData;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class notifyDataInfoResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CMMB.ESBService.namespace", Order=0)]
    public int notifyResponse;
    
    public notifyDataInfoResponse()
    {
    }
    
    public notifyDataInfoResponse(int notifyResponse)
    {
        this.notifyResponse = notifyResponse;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getManufacturerInfoRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CMMB.ESBService.namespace", Order=0)]
    public requestHead requestHead;
    
    public getManufacturerInfoRequest()
    {
    }
    
    public getManufacturerInfoRequest(requestHead requestHead)
    {
        this.requestHead = requestHead;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getManufacturerInfoResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CMMB.ESBService.namespace", Order=0)]
    [System.Xml.Serialization.XmlArrayItemAttribute("manufacturer", IsNullable=false)]
    public manufacturerInfoType[] manufacturerInfoList;
    
    public getManufacturerInfoResponse()
    {
    }
    
    public getManufacturerInfoResponse(manufacturerInfoType[] manufacturerInfoList)
    {
        this.manufacturerInfoList = manufacturerInfoList;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class notifyUploadEventRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CMMB.ESBService.namespace", Order=0)]
    public requestHead requestHead;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CMMB.ESBService.namespace", Order=1)]
    public int uploadEventResult;
    
    public notifyUploadEventRequest()
    {
    }
    
    public notifyUploadEventRequest(requestHead requestHead, int uploadEventResult)
    {
        this.requestHead = requestHead;
        this.uploadEventResult = uploadEventResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class notifyUploadEventResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CMMB.ESBService.namespace", Order=0)]
    public int uploadResponse;
    
    public notifyUploadEventResponse()
    {
    }
    
    public notifyUploadEventResponse(int uploadResponse)
    {
        this.uploadResponse = uploadResponse;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface DeviceInterfaceChannel : DeviceInterface, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class DeviceInterfaceClient : System.ServiceModel.ClientBase<DeviceInterface>, DeviceInterface
{
    
    public DeviceInterfaceClient()
    {
    }
    
    public DeviceInterfaceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public DeviceInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DeviceInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DeviceInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    getDeviceTypesResponse DeviceInterface.getDeviceTypes(getDeviceTypesRequest request)
    {
        return base.Channel.getDeviceTypes(request);
    }
    
    public deviceTypeInfo[] getDeviceTypes(requestHead requestHead)
    {
        getDeviceTypesRequest inValue = new getDeviceTypesRequest();
        inValue.requestHead = requestHead;
        getDeviceTypesResponse retVal = ((DeviceInterface)(this)).getDeviceTypes(inValue);
        return retVal.deviceTypeList;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    getDeviceParameterDefinitionResponse DeviceInterface.getDeviceParameterDefinition(getDeviceParameterDefinitionRequest request)
    {
        return base.Channel.getDeviceParameterDefinition(request);
    }
    
    public deviceParameterList getDeviceParameterDefinition(requestHead requestHead, string deviceTypeCode)
    {
        getDeviceParameterDefinitionRequest inValue = new getDeviceParameterDefinitionRequest();
        inValue.requestHead = requestHead;
        inValue.deviceTypeCode = deviceTypeCode;
        getDeviceParameterDefinitionResponse retVal = ((DeviceInterface)(this)).getDeviceParameterDefinition(inValue);
        return retVal.deviceParameterList;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    notifyDataInfoResponse DeviceInterface.notifyDataInfo(notifyDataInfoRequest request)
    {
        return base.Channel.notifyDataInfo(request);
    }
    
    public int notifyDataInfo(requestHead requestHead, notifyData notifyData)
    {
        notifyDataInfoRequest inValue = new notifyDataInfoRequest();
        inValue.requestHead = requestHead;
        inValue.notifyData = notifyData;
        notifyDataInfoResponse retVal = ((DeviceInterface)(this)).notifyDataInfo(inValue);
        return retVal.notifyResponse;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    getManufacturerInfoResponse DeviceInterface.getManufacturerInfo(getManufacturerInfoRequest request)
    {
        return base.Channel.getManufacturerInfo(request);
    }
    
    public manufacturerInfoType[] getManufacturerInfo(requestHead requestHead)
    {
        getManufacturerInfoRequest inValue = new getManufacturerInfoRequest();
        inValue.requestHead = requestHead;
        getManufacturerInfoResponse retVal = ((DeviceInterface)(this)).getManufacturerInfo(inValue);
        return retVal.manufacturerInfoList;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    notifyUploadEventResponse DeviceInterface.notifyUploadEvent(notifyUploadEventRequest request)
    {
        return base.Channel.notifyUploadEvent(request);
    }
    
    public int notifyUploadEvent(requestHead requestHead, int uploadEventResult)
    {
        notifyUploadEventRequest inValue = new notifyUploadEventRequest();
        inValue.requestHead = requestHead;
        inValue.uploadEventResult = uploadEventResult;
        notifyUploadEventResponse retVal = ((DeviceInterface)(this)).notifyUploadEvent(inValue);
        return retVal.uploadResponse;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://CMMB.ESBService.namespace", ConfigurationName="MonitorObjInterface")]
public interface MonitorObjInterface
{
    
    // CODEGEN: 操作 getMonitorObjStatus 以后生成的消息协定不是 RPC，也不是换行文档。
    [System.ServiceModel.OperationContractAttribute(Action="getMonitorObjStatus")]
    [System.ServiceModel.FaultContractAttribute(typeof(cmmb.esbservice.@namespace.faultMessage), Action="getMonitorObjStatus", Name="faultMessage")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    getMonitorObjStatusResponse getMonitorObjStatus(getMonitorObjStatusRequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getMonitorObjStatusRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CMMB.ESBService.namespace", Order=0)]
    public requestHead requestHead;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CMMB.ESBService.namespace", Order=1)]
    public string monitorObjCode;
    
    public getMonitorObjStatusRequest()
    {
    }
    
    public getMonitorObjStatusRequest(requestHead requestHead, string monitorObjCode)
    {
        this.requestHead = requestHead;
        this.monitorObjCode = monitorObjCode;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getMonitorObjStatusResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CMMB.ESBService.namespace", Order=0)]
    public int getStatusResponse;
    
    public getMonitorObjStatusResponse()
    {
    }
    
    public getMonitorObjStatusResponse(int getStatusResponse)
    {
        this.getStatusResponse = getStatusResponse;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface MonitorObjInterfaceChannel : MonitorObjInterface, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class MonitorObjInterfaceClient : System.ServiceModel.ClientBase<MonitorObjInterface>, MonitorObjInterface
{
    
    public MonitorObjInterfaceClient()
    {
    }
    
    public MonitorObjInterfaceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public MonitorObjInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MonitorObjInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MonitorObjInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    getMonitorObjStatusResponse MonitorObjInterface.getMonitorObjStatus(getMonitorObjStatusRequest request)
    {
        return base.Channel.getMonitorObjStatus(request);
    }
    
    public int getMonitorObjStatus(requestHead requestHead, string monitorObjCode)
    {
        getMonitorObjStatusRequest inValue = new getMonitorObjStatusRequest();
        inValue.requestHead = requestHead;
        inValue.monitorObjCode = monitorObjCode;
        getMonitorObjStatusResponse retVal = ((MonitorObjInterface)(this)).getMonitorObjStatus(inValue);
        return retVal.getStatusResponse;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://CMMB.ESBService.namespace", ConfigurationName="MaintenanceInterface")]
public interface MaintenanceInterface
{
    
    // CODEGEN: 操作 sendMTAMessage 以后生成的消息协定不是 RPC，也不是换行文档。
    [System.ServiceModel.OperationContractAttribute(Action="sendMTAMessage")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    sendMTAMessageResponse sendMTAMessage(sendMTAMessageRequest request);
    
    // CODEGEN: 操作 getMTAExtendableDef 以后生成的消息协定不是 RPC，也不是换行文档。
    [System.ServiceModel.OperationContractAttribute(Action="getMTAExtendableDef")]
    [System.ServiceModel.FaultContractAttribute(typeof(cmmb.esbservice.@namespace.faultMessage), Action="getMTAExtendableDef", Name="faultMessage")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    getMTAExtendableDefResponse getMTAExtendableDef(getMTAExtendableDefRequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class sendMTAMessageRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CMMB.ESBService.namespace", Order=0)]
    public requestHead requestHead;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CMMB.ESBService.namespace", Order=1)]
    public messageDataType mtaMessageData;
    
    public sendMTAMessageRequest()
    {
    }
    
    public sendMTAMessageRequest(requestHead requestHead, messageDataType mtaMessageData)
    {
        this.requestHead = requestHead;
        this.mtaMessageData = mtaMessageData;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class sendMTAMessageResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CMMB.ESBService.namespace", Order=0)]
    public int notifyResponse;
    
    public sendMTAMessageResponse()
    {
    }
    
    public sendMTAMessageResponse(int notifyResponse)
    {
        this.notifyResponse = notifyResponse;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getMTAExtendableDefRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CMMB.ESBService.namespace", Order=0)]
    public requestHead requestHead;
    
    public getMTAExtendableDefRequest()
    {
    }
    
    public getMTAExtendableDefRequest(requestHead requestHead)
    {
        this.requestHead = requestHead;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getMTAExtendableDefResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CMMB.ESBService.namespace", Order=0)]
    public mtaDataExtenableDefType mtaDataExtensionDef;
    
    public getMTAExtendableDefResponse()
    {
    }
    
    public getMTAExtendableDefResponse(mtaDataExtenableDefType mtaDataExtensionDef)
    {
        this.mtaDataExtensionDef = mtaDataExtensionDef;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface MaintenanceInterfaceChannel : MaintenanceInterface, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class MaintenanceInterfaceClient : System.ServiceModel.ClientBase<MaintenanceInterface>, MaintenanceInterface
{
    
    public MaintenanceInterfaceClient()
    {
    }
    
    public MaintenanceInterfaceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public MaintenanceInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MaintenanceInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MaintenanceInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    sendMTAMessageResponse MaintenanceInterface.sendMTAMessage(sendMTAMessageRequest request)
    {
        return base.Channel.sendMTAMessage(request);
    }
    
    public int sendMTAMessage(requestHead requestHead, messageDataType mtaMessageData)
    {
        sendMTAMessageRequest inValue = new sendMTAMessageRequest();
        inValue.requestHead = requestHead;
        inValue.mtaMessageData = mtaMessageData;
        sendMTAMessageResponse retVal = ((MaintenanceInterface)(this)).sendMTAMessage(inValue);
        return retVal.notifyResponse;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    getMTAExtendableDefResponse MaintenanceInterface.getMTAExtendableDef(getMTAExtendableDefRequest request)
    {
        return base.Channel.getMTAExtendableDef(request);
    }
    
    public mtaDataExtenableDefType getMTAExtendableDef(requestHead requestHead)
    {
        getMTAExtendableDefRequest inValue = new getMTAExtendableDefRequest();
        inValue.requestHead = requestHead;
        getMTAExtendableDefResponse retVal = ((MaintenanceInterface)(this)).getMTAExtendableDef(inValue);
        return retVal.mtaDataExtensionDef;
    }
}
namespace cmmb.esbservice.@namespace
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="faultMessage", Namespace="http://CMMB.ESBService.namespace")]
    public partial class faultMessage : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int FaultCodeField;
        
        private string FaultDescField;
        
        private string FaultReasonField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int FaultCode
        {
            get
            {
                return this.FaultCodeField;
            }
            set
            {
                this.FaultCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string FaultDesc
        {
            get
            {
                return this.FaultDescField;
            }
            set
            {
                this.FaultDescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string FaultReason
        {
            get
            {
                return this.FaultReasonField;
            }
            set
            {
                this.FaultReasonField = value;
            }
        }
    }
}
