<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2005 sp2 U (http://www.altova.com) by any (Ru-Board) -->
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:y="http://JSTV/PlatfromService/QueryIntegerationService" xmlns:ns="http://JSTV/MediaEntityDefinition/" xmlns:ns1="http://JSTV/PlatformService/Parameter/" targetNamespace="http://JSTV/PlatfromService/QueryIntegerationService">
	<types>
		<xs:schema xmlns:tns="http://JSTV/PlatformService/Parameter/">
			<xs:import namespace="http://JSTV/PlatformService/Parameter/" schemaLocation="PlatformServiceParameter.xsd"/>
		</xs:schema>
	</types>
	<message name="UnifyClockRequestMessage">
		<part name="UnifyClockRequest" element="ns1:UnifyClockRequest"/>
	</message>
	<message name="UnifyClockResponseMessage">
		<part name="UnifyClockResponse" element="ns1:UnifyClockResponse"/>
	</message>
	<portType name="UnifyClockPortType">
		<operation name="unify">
			<input message="y:UnifyClockRequestMessage"/>
			<output message="y:UnifyClockResponseMessage"/>
		</operation>
	</portType>
	<binding name="UnifyClockBinding" type="y:UnifyClockPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="unify">
			<input>
				<soap:body use="literal"/>
			</input>
			<output>
				<soap:body use="literal"/>
			</output>
		</operation>
	</binding>
	<service name="UnifyClockService">
		<port name="UnifyClockPort" binding="y:UnifyClockBinding">
			<soap:address location="No Target Adress"/>
		</port>
	</service>
</definitions>
